# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BSP_NXP_DERIVED ??= ""
# We have a packages directory, add to BBFILES
BBFILES += "${@bb.utils.contains_any('MACHINE', '${BSP_NXP_DERIVED}', '${LAYERDIR}/recipes-*/*/*.bb', '', d)}"
BBFILES += "${@bb.utils.contains_any('MACHINE', '${BSP_NXP_DERIVED}', '${LAYERDIR}/recipes-*/*/*.bbappend', '', d)}"

BBFILE_COLLECTIONS += "imx-machine-learning"
BBFILE_PATTERN_imx-machine-learning := "^${LAYERDIR}/"
BBFILE_PRIORITY_imx-machine-learning = "8"

LAYERDEPENDS_meta-ml = "core freescale-layer"

LAYERSERIES_COMPAT_imx-machine-learning = "mickledore nanbield scarthgap styhead"
